### ISSUE TITLE
madqt with a custom version of tao

### ISSUE THREAD

**Issue by DavidSagan** [hibtc/madgui#14]
Hi David,

I’ve been playing with pytao and tried to run our recycler case. I customized tao to use Ming-Jen’s hooks to read in the extra data files we need and ran successfully. 

Do we have a way yet of using custom tao version with pytao or an idea of how to do this?

From what I understand from Ming, the custom commands are basically for reading in data files, is this something I should do from python instead?

Cheers,

Rob

**Comment by DavidSagan** [comment]
There are two sides to this: On the Tao/Bmad side, instead of compiling the custom code separately, the custom code could be placed in the tao/hook or bmad/custom directories replacing the corresponding dummy routines so that the tao and bmad libraries will contain the custom code. 

This is the simplest but not necessarily the most elegant solution. A cleaner solution would involve some mechanism so that pytao could be instructed to install itself using the custom code. 

On the gui side, it depends upon what the custom code is doing. If the custom code is not affecting the API of tao then nothing needs to be done. For example, code for custom tracking of particles has no effect on the gui.

In Robert's case, the custom code is used to implement custom commands and this does affect the api. The simplest solution here is to have a window with a text box so strings could be directly set to tao. This would be of general usefulness so the gui should make available such a window in any case.

A more elegant way would involve custom python code spliced in with the gui base code. In this case, what is wanted is a custom window where the data file can be selected. The base code should be organized so that the custom gui code can be put in a separate file. This minimizes maintenance headaches when the base code changes.

**Comment by rainswor** [comment]
For now the hooks were placed in tao/program. With the custom build in place, can I use the custom commands with pytao using

```
tao = Tao('-lat', lattice, '-noplot', '-gui_mode')
tao.command(custom command)
```

to achieve the desired result? Or do i need to do modify the pytao build in some way?

**Comment by DavidSagan** [comment]
Placing the custom code in tao/program will not work since they will not get compiled into libtao. You need to put them in tao/hook replacing the dummy routines (so that there are not both dummy and modified routines with the same name in libtao). 

After you have moved the code, reinstall pytao ("pyton setup.py ...") and the commands in your post should work.

**Comment by DavidSagan** [comment]
By the way, Even with your custom code in tao/hook you can safely do "svn update" to update tao.

**Comment by coldfix** [comment]
> Do we have a way yet of using custom tao version with pytao or an idea of how to do this?

I don't know your exact setup, but I don't see any reason why you shouldn't be able to link pytao against that custom version - unless you made serious changes to how tao works internally.

> From what I understand from Ming, the custom commands are basically for reading in data files, is this something I should do from python instead?

It depends on how much code you'd have to rewrite for that and where you want to process which data. For me the point of pytao is that it's much easier and efficient to write application logic in python and doesn't require recompiling after every change, so yes, I'd usually prefer adding logic as a python program rather than creating a tao variant. But of course, it depends on your use case.



> For now the hooks were placed in tao/program. With the custom build in place, can I use the custom commands with pytao using
>
> tao = Tao('-lat', lattice, '-noplot', '-gui_mode')
> tao.command(custom command)
>
> to achieve the desired result? Or do i need to do modify the pytao build in some way?

Yes, it should work. The `tao.command` function currently just passes text to tao's interpreter. So as long as tao itselfs knows the command it should work.

**Comment by DavidSagan** [comment]
>> Do we have a way yet of using custom tao version with pytao or an idea of how to do this?

> I don't know your exact setup, but I don't see any reason why you shouldn't be able to link pytao against that custom version - unless you made serious changes to how tao works internally.

The issue here is that the standard way to create a custom version of tao (that is, a custom executable) does not modify libtao. The custom executable is formed by just linking the custom code along with the unaltered libtao . When pytao is initialized, this custom code is then ignored which is not what is wanted. If there was a way to tell pytao about the custom code at initialization time this would solve the problem. The alternative is to put the custom code into libtao which is not as clean but certainly does not need for pytao to be altered to handle custom tao/bmad code.

>>From what I understand from Ming, the custom commands are basically for reading in data files, is this something I should do from python instead?

>It depends on how much code you'd have to rewrite for that and where you want to process which data. For me the point of pytao is that it's much easier and efficient to write application logic in python and doesn't require recompiling after every change, so yes, I'd usually prefer adding logic as a python program rather than creating a tao variant. But of course, it depends on your use case.

Once custom tao/bmad code has been developed to do a certain task it tends to be stable so recompiling should not be an issue. But your point is a good one that in the future people can choose to develop customizations on either side  (or both!). In the present case, since the Fermilab custom code is already developed, it does not make sense to try to recreate it on the python side. 

This brings up the issue of how best to structure things if someone wants to custimize the gui...

**Comment by coldfix** [comment]
> The issue here is that the standard way to create a custom version of tao (that is, a custom executable) does not modify libtao. The custom executable is formed by just linking the custom code along with the unaltered libtao . When pytao is initialized, this custom code is then ignored which is not what is wanted. If there was a way to tell pytao about the custom code at initialization time this would solve the problem.

If it's just linking, you can add your custom lib to the pytao libraries, like `python setup.py build_ext -lNAME`

**Comment by DavidSagan** [comment]
There is no custom lib though. Just files containing custom code. Is there a syntax for linking in individual files? I guess a custom lib could be created but that would be an extra step.

**Comment by coldfix** [comment]
I think this is outside the scope of madqt. Creating a custom lib can be done conveniently outside. Otherwise, you'll have to modify `setup.py` to build your files.
