### ISSUE TITLE
Cannot change lattice element real attribute

### ISSUE THREAD

**Issue by DavidSagan** [hibtc/madgui#16]
I can select a real attribute of a lattice element but I cannot change it.

**Comment by coldfix** [comment]
Element info boxes are still read-only, but this is the next thing I will work on.

**Comment by coldfix** [comment]
Did some reorganization of the way data is written. It's not final and some parts will definitely be broken, but at least you should be able to write some element attributes now.

I will have to do a lot bugfixes and UI improvements, though.

By the way, is there a way to decide which attributes are mutable? The T/F flag doesn't seem to be entirely suitable for this purpose, in particular e.g. for beam initial settings.

**Comment by DavidSagan** [comment]
>By the way, is there a way to decide which attributes are mutable? The T/F flag doesn't seem to be entirely suitable for this purpose, in particular e.g. for beam initial settings.

I'm a little confused here. Why are not the T/F flags suitable?

**Comment by coldfix** [comment]
> I'm a little confused here. Why are not the T/F flags suitable?

Ok, this might be a special case, maybe I'm using the incorrect command. Trying to change beam/particle initial conditions:

```
Tao> python lat_ele1 1@0>>0|model twiss
beta_a;REAL;F;  4.4000000000000000E+01
alpha_a;REAL;F; -7.0000000000000000E+00
...

Tao> set element 1@0>>0 beta_a = 0.1

Tao> python lat_ele1 1@0>>0|model twiss
beta_a;REAL;F;  1.0000000000000001E-01
...
```

So this seems to work even though `F` is given. Also, I got a bit confused by the fact that in order to change the attributes corresponding to `lat_ele1 ... orbit`, I need the `change beam_start KEY @VAL` syntax.

What is the difference between `change` and `set`?

By the way, there is some garbage data in the output for `SPIN_FRINGE_ON`:

```
Tao> python lat_ele1 1@0>>1|model parameters
...
SPIN_FRINGE_ON;LOGIC;T;
...
```

For reference, I'm using the simple lattice example you posted some time ago:

```
parameter[particle] = #12C+6
parameter[geometry] = open

beginning[e_tot]    = 400e+9

beginning[beta_a]   = 44
beginning[beta_b]   = 4
beginning[alpha_a]  = -7
beginning[alpha_b]  = -1

bb: sbend, l = 2, angle = 1
oo: overlay = {bb}, g_err

seq: line = (bb)

use, seq
```

**Comment by DavidSagan** [comment]
>Ok, this might be a special case, maybe I'm using the incorrect command.

The problem was that Bmad was not properly marking beta_a for element 0 as variable. I have fixed this. Some of the code here is new so bugs are to be expected. Just drop me a line if you see any other problems.

 >What is the difference between change and set?

There is some overlap between the two commands. Essentially "change" is used to change real valued parameters by a delta given by the user. "Set" is used to set both real and non-real parameters. To simplify things you can just ignore the "change" command.

>By the way, there is some garbage data in the output for SPIN_FRINGE_ON:

Fixed.

**Comment by coldfix** [comment]
Great, thanks.

**Comment by coldfix** [comment]
madqt is now using the `vary` flag from tao to indicate whether something is `editable`. Properties that can't be varied are shown in gray, so you can spot more easily if the settings are appropriate.

**Comment by DavidSagan** [comment]
I'm not able to vary real valued parameters. What is the situation with this?

**Comment by coldfix** [comment]
If it is grayed out, it is because of tao reporting it with the F flag. If that's not the case, tell me which one specifically and I will investigate.

**Comment by coldfix** [comment]
(did you git pull the latest version?)

**Comment by DavidSagan** [comment]
Yes I do have the latest version. And it is not grayed out. See the attached screen shot. I am able to toggle T/F values. And I am able to select real values but I cannot change them. Also there is no pull down menu for enum parameters.


![screen shot 2017-06-09 at 1 00 49 pm](https://user-images.githubusercontent.com/1026006/26986036-e7ceb496-4d13-11e7-944f-04a3ac60375d.png)

**Comment by coldfix** [comment]
Did you rebuild pytao (`touch pytao/tao_pipe.c && python setup.py develop`) after making changes to bmad/tao?

**Comment by DavidSagan** [comment]
Yes in fact I deleted and then remade pytao just to make sure.

**Comment by coldfix** [comment]
Ok. What exactly happens when you double click enums? Does it select the value in a text edit as with the other values, or does it do something else?

**Comment by DavidSagan** [comment]
It selects as with text edit.

**Comment by DavidSagan** [comment]
If you want we could skype and I could share my screen...

**Comment by DavidSagan** [comment]
OK if I build a native version of madqt on my mac I can change real valued parameters. The problem only shows when I ssh from my mac to Linux (SL 7 to be exact) and run madqt from Linux.

**Comment by coldfix** [comment]
do you `ssh -X` or `ssh -Y`?

**Comment by DavidSagan** [comment]
ssh -Y

**Comment by DavidSagan** [comment]
The following simple program also displays the problem. If I run the program from Linux I cannot enter text but if I run natively from my mac everything is OK



```
import sys
from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget, QPushButton, QAction, QLineEdit, QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot
 
class App(QMainWindow):
 
    def __init__(self):
        super().__init__()
        self.title = 'PyQt5 textbox - pythonspot.com'
        self.left = 10
        self.top = 10
        self.width = 400
        self.height = 140
        self.initUI()
 
    def initUI(self):
        self.setWindowTitle(self.title)
        self.setGeometry(self.left, self.top, self.width, self.height)
 
        # Create textbox
        self.textbox = QLineEdit(self)
        self.textbox.move(20, 20)
        self.textbox.resize(280,40)
 
        # Create a button in the window
        self.button = QPushButton('Show text', self)
        self.button.move(20,80)
 
        # connect button to function on_click
        self.button.clicked.connect(self.on_click)
        self.show()
 
    @pyqtSlot()
    def on_click(self):
        textboxValue = self.textbox.text()
        QMessageBox.question(self, 'Message - pythonspot.com', "You typed: " + textboxValue, QMessageBox.Ok, QMessageBox.Ok)
        self.textbox.setText("")
 
 
if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = App()
    sys.exit(app.exec_())
```

**Comment by coldfix** [comment]
Ok. In this case I don't see what I can do about this. By the way, this works for me over SSH linux to linux, both `-X` and `-Y`.

**Comment by coldfix** [comment]
(Does it work if you replace PyQt5 for PyQt4?)

**Comment by DavidSagan** [comment]
I tried this connecting to linux via X2Go. In this case got the error messages:

```
erpsim1:~/dcs16/TaoGui/test> python tt.py 
failed to get the current screen resources
Qt: Could not determine keyboard configuration data from X server, will use hard-coded keymap configuration.
QXcbConnection: XCB error: 172 (Unknown), sequence: 168, resource id: 163, major code: 149 (Unknown), minor code: 20
```

I could type text in this case but the displayed text did not match what I typed.

**Comment by DavidSagan** [comment]
pyqt4 with python 2.7 does not have the problem!

**Comment by coldfix** [comment]
Ok. Just FYI, you can force madqt to use PyQt4 (if installed) by specifying the `PYQT_API` environment variable:

```
PYQT_API=pyqt  madqt /path/to/lattice  # PyQt4
PYQT_API=pyqt5 madqt /path/to/lattice  # PyQt5
```

I might also add command line switch/config file option for that.
