### ISSUE TITLE
Tao specific constructs

### ISSUE THREAD

**Issue by DavidSagan** [hibtc/madgui#25]
@coldfix 
After being sidetracked I am back to getting data and variable windows implemented. One issue is that MAD's concept of data and variable is quite limited in comparison. My thought is that I would work on  setting up data and variable windows for when Tao is used. Eventually corresponding windows could be coded for when MAD is used. And ultimately native madqt constructs could be implemented. 

What do you think? Also there is the whole issue of multiple models and multiple measurements (see issue #17). Have you had any thoughts on this?

Cheers, David

**Comment by coldfix** [comment]
> My thought is that I would work on setting up data and variable windows for when Tao is used. Eventually corresponding windows could be coded for when MAD is used. And ultimately native madqt constructs could be implemented.

Ok, go ahead to implement it for tao only right now, we will see later how to fit it in with the rest.

> Also there is the whole issue of multiple models and multiple measurements (see issue #17). Have you had any thoughts on this?

More on this in #17.
